spring:
  application:
    name: zerobug-agent

  datasource:
    url: jdbc:postgresql://database-1.crg8g8eyy9ib.ap-southeast-1.rds.amazonaws.com:5432/
    username: postgres
    password: Hoa230969
    driver-class-name: org.postgresql.Driver
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: ${SERVER_PORT:8080}

zerobug:
  admin:
    email: admin@gmail.com
    password: Admin@123456
    full-name: System Admin
  storage:
    type: ${STORAGE_TYPE:local}
    path: ${STORAGE_PATH:./data/projects}
    s3-bucket: ${S3_BUCKET:}
    s3-region: ${AWS_REGION:ap-southeast-1}
  app:
    base-url: ${APP_BASE_URL:http://localhost:8080}
  mail:
    dev-mode: ${MAIL_DEV_MODE:true}
  aws:
    enabled: true
    region: ap-southeast-1
    bedrock-region: ap-southeast-1
    knowledge-base-id: ${BEDROCK_KNOWLEDGE_BASE_ID:} # Để trống hoặc nhận từ biến môi trường
    data-source-id: ${BEDROCK_DATA_SOURCE_ID:}
    model-id: ${BEDROCK_MODEL_ID:google.gemma-3-12b-instruct-v1:0}
logging:
  level:
    com.testbuddy: INFO
